services:
  client:
    image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/scrunchy-client:latest
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - server
    restart: unless-stopped

  server:
    image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/scrunchy-server:latest
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=harsh1592
      - DB_NAME=scrunchy
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET=
      - PAY_ID=
      - PAY_SECRET=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_CALLBACK_URL=https://scrunchy.harshthakur.site/api/auth/callback?provider=google
      - REDIRECT_SECURE=https://scrunchy.harshthakur.site
      - SESSION_COOKIE_DOMAIN=scrunchy.harshthakur.site
      - ENV=production
    networks:
      - app-network
    ports:
      - "3001:3000"
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harsh1592
      POSTGRES_DB: scrunchy
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
    driver: local
  uploads-data:
    driver: local

networks:
  app-network:
    driver: bridge
