services:
  client:
    # image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/scrunchy-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=${ENV}
    networks:
      - app-network
    depends_on:
      - server
    restart: unless-stopped

  server:
    # image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/scrunchy-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET=${SECRET}
      - PAY_ID=${PAY_ID}
      - PAY_SECRET=${PAY_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - REDIRECT_SECURE=${REDIRECT_SECURE}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
      - ENV=${ENV}
    networks:
      - app-network
    ports:
      - "3001:3000"
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
    driver: local
  uploads-data:
    driver: local

networks:
  app-network:
    driver: bridge
